version: '3'
services:
  db:
    image: mysql:5.7.23
    restart: always
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: docker
    volumes:
      - ./backend/db/mysql/volumes:/var/lib/mysql
  backend:
    build: ./backend
    ports:
      - 3000:3000
    command: bash -c "rm -rf /app/tmp/pids/server.pid && (bundle check || bundle install) && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - ./backend/.env
    tty: true
    stdin_open: true
  frontend:
    build: ./frontend
    tty: true
    ports:
      - 8000:3000
    command: npm run dev
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env