

###
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6InNrSUJOZyJ9.eyJpc3MiOiJodHRwczovL2lkZW50aXR5dG9vbGtpdC5nb29nbGUuY29tLyIsImF1ZCI6Im51eHQtcmFpbHMtZmlyZWF1dGgtc2FtcGxlIiwiaWF0IjoxNTcwMDA5MTU0LCJleHAiOjE1NzEyMTg3NTQsInVzZXJfaWQiOiJLYTlSUkpjTVRZTXNqRm9ONUFGSzJjTHBoTDUyIiwiZW1haWwiOiJhYWFAYWFhLmNvbSIsInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCIsInZlcmlmaWVkIjpmYWxzZX0.GIKCFZgvqEidp9csVUx8yhx0ixsBjIAga-Tr8zLxTiCDNY066Wfp_7m_ZVEFhnNn98qy_lCjuHFtctaBHQXUsYg7GtH3SZtHEsLrdsOGUoQaHUtx9cjoGpK7H96NnIeXSlEEUm_eCoEu_Iwiepd9VZ6UnRnUg2sCS4EHdygehrTJPTdYy9ghd_iLJUYhU29fQrD9V7ELdc8Kpqn6HQNorW2oBjrUoE_K1lehNRnb-8QcQvLydaqY1RBNbuLB7Fd9A0znQ_ov9ymcuyaT5z6NnCVNZaLZdCTzPQeZnhd9IbivpaO4s0vLphbaHhaCWmSB6vg5891IRj39n0KMMOsGLw
GET http://localhost:3010/articles HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:3010/articles HTTP/1.1
content-type: application/json
Authorization: Bearer invalid

